apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jama.fullname" . }}-config
  namespace: {{ include "jama.namespace" . }}
  labels:
    {{- include "jama.labels" . | nindent 4 }}
data:
  JAMA_FQDN: {{ .Values.global.fqdn | quote }}
  JAMA_BASE_URL: {{ printf "https://%s" .Values.global.fqdn | quote }}
  {{- range $k, $v := .Values.appConfig }}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
